/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as crowSaleSol from "./CrowSale.sol";
export type { crowSaleSol };
import type * as nftCardSol from "./NFTCard.sol";
export type { nftCardSol };
export type { Auction } from "./Auction";
export type { BNBT } from "./BNBT";
export type { NFTAuction } from "./NFTAuction";
export type { NFTCardMarketplace } from "./NFTCardMarketplace";
export type { USDT } from "./USDT";
