/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IDNFTCard2,
  IDNFTCard2Interface,
} from "../../../contracts/NFTCard2.sol/IDNFTCard2";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "nftCard2_type",
        type: "uint256",
      },
    ],
    name: "mint",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IDNFTCard2__factory {
  static readonly abi = _abi;
  static createInterface(): IDNFTCard2Interface {
    return new utils.Interface(_abi) as IDNFTCard2Interface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IDNFTCard2 {
    return new Contract(address, _abi, signerOrProvider) as IDNFTCard2;
  }
}
