/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IDNFTCard2__factory } from "./IDNFTCard2__factory";
export { NFTCard2__factory } from "./NFTCard2__factory";
