/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IDNFTCard1,
  IDNFTCard1Interface,
} from "../../../contracts/NFTCard1.sol/IDNFTCard1";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "nftCard1_type",
        type: "uint256",
      },
    ],
    name: "mint",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IDNFTCard1__factory {
  static readonly abi = _abi;
  static createInterface(): IDNFTCard1Interface {
    return new utils.Interface(_abi) as IDNFTCard1Interface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IDNFTCard1 {
    return new Contract(address, _abi, signerOrProvider) as IDNFTCard1;
  }
}
