/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IDNFTCard1__factory } from "./IDNFTCard1__factory";
export { NFTCard1__factory } from "./NFTCard1__factory";
