/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IDNFTCard,
  IDNFTCardInterface,
} from "../../../contracts/NFTCard.sol/IDNFTCard";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "nftCard_type",
        type: "uint256",
      },
    ],
    name: "mint",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IDNFTCard__factory {
  static readonly abi = _abi;
  static createInterface(): IDNFTCardInterface {
    return new utils.Interface(_abi) as IDNFTCardInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IDNFTCard {
    return new Contract(address, _abi, signerOrProvider) as IDNFTCard;
  }
}
