/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IDNFTCard__factory } from "./IDNFTCard__factory";
export { NFTCard__factory } from "./NFTCard__factory";
